baseURL = "https://obiserra.github.io/"
languageCode = "en-us"
title = "obiserra - blog"
theme = "vec"


[menu]
  # Shown in the side menu.
  
  [[menu.main]] 
    name = "post"
    url = "/posts"
  [[menu.main]] 
    name = "download_cv"
    url = "https://github.com/obiSerra/resume/raw/master/output/Roberto_Serra_CV.pdf"


[params]
  Keywords = "programming"
  Description = "There are some words to describe your site"
  Avatar = "img/avatar-face.png"
  SelfIntro = "Do. Or do not. There is no try."
  Email = "obi.serra@gmail.com"

  GithubID = "obiSerra"
  LinkedInID = "obiserra"
